-- Export script: ModEquivalencies
-- Reads ModEquivalencies.datc64 and writes src/Data/ModEquivalencies.lua
-- Run via the PoB export tool (same way as other Scripts/*.lua files).
--
-- ModEquivalencies maps each source mod to its upgraded equivalent.
-- Used by Way of the Stonefist (CalcPerform) to transform glove explicit mods.
--
-- IMPORTANT — FORMAT MISMATCH (must be fixed before this script generates valid data):
--
--   CalcPerform.lua looks up equivalencies by raw mod line TEXT:
--     equivalencies[modLine.line]   -- e.g. "(80-100)% increased Armour"
--
--   This script currently writes MOD ID keys:
--     ["some_mod_id"] = "equiv_mod_id"
--
--   These two formats are INCOMPATIBLE. The generated file will produce an
--   all-miss lookup table and the feature will remain a no-op even after export.
--
--   To fix, update this script so that each key is the stat description text
--   exactly as it appears in src/Data/Uniques/gloves.lua for the source mod
--   (range format, e.g. "(80-100)% increased Armour"), and each value is the
--   resolved stat description text for the upgraded equivalent (single value,
--   no range notation, e.g. "150% increased Armour").
--
--   Reference: CalcPerform.lua comment block above GloveExplicitModTransform,
--   and src/Data/ModEquivalencies.lua header.
--
-- Expected datc64 schema (PoE2):
--   ModsKey          : ref to Mods (the source mod being replaced)
--   EquivalentModsKey: ref to Mods (the upgraded replacement mod)

local out = io.open("../Data/ModEquivalencies.lua", "w")
out:write("-- This file is automatically generated, do not edit!\n")
out:write("-- Item data (c) Grinding Gear Games\n\n")
out:write("-- Maps source mod text (range format) -> upgraded equivalent mod text (resolved).\n")
out:write("-- See script header for format requirements before re-running this export.\n")
out:write("return {\n")

local count = 0
for row in dat("ModEquivalencies"):Rows() do
	local srcMod = row.ModsKey
	local dstMod = row.EquivalentModsKey

	if srcMod and dstMod and srcMod.Id and dstMod.Id then
		-- TODO: replace srcMod.Id / dstMod.Id with the stat description text
		-- for each mod, formatted to match modLine.line in CalcPerform.lua.
		out:write('\t-- ["<src text>"] = "<dst text>",  -- ', srcMod.Id, ' -> ', dstMod.Id, '\n')
		count = count + 1
	end
end

out:write("}\n")
out:close()

ConPrintf("ModEquivalencies: found %d entries (all written as TODO comments — see script header)", count)
if count == 0 then
	ConPrintf("WARNING: 0 entries found. Check field names ModsKey/EquivalentModsKey match the datc64 schema.")
end
